"""Compiler Engine: Generates Pydantic Models, JSON Schemas, DSPy Signatures, and Promptfoo YAML."""

from __future__ import annotations

import ast
import json
import re
from typing import Any


def _sanitize_class_name(title: str, default: str = "PromptResponse") -> str:
    cleaned = re.sub(r"[^a-zA-Z0-9 ]", "", title).strip()
    if not cleaned:
        return default
    words = cleaned.split()
    name = "".join(w.capitalize() for w in words) or default
    if name and name[0].isdigit():
        name = f"Model{name}"
    return name


def _sanitize_slug(title: str, default: str = "prompt") -> str:
    cleaned = re.sub(r"[^a-zA-Z0-9_-]", "-", title.lower()).strip("-")
    return cleaned[:40] or default


def compile_pydantic_model(title: str, prompt: str, extra_fields: dict[str, str] | None = None) -> tuple[str, bool]:
    class_name = _sanitize_class_name(title, "PromptResponse")
    summary = prompt.replace('"""', '\\"\\"\\"').strip()[:100]

    code = f'''"""Pydantic model generated by PromptBuddy Enterprise."""
from pydantic import BaseModel, Field


class {class_name}(BaseModel):
    """Structured response schema for: {summary}"""

    reasoning: str = Field(
        ...,
        description="Step-by-step reasoning or chain-of-thought before the final answer."
    )
    answer: str = Field(
        ...,
        description="The final actionable answer conforming to the prompt specification."
    )
    confidence: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
        description="Confidence score between 0.0 and 1.0."
    )
    sources: list[str] = Field(
        default_factory=list,
        description="References, sources, or citations used."
    )
'''
    if extra_fields:
        for fname, fdesc in extra_fields.items():
            safe_fname = re.sub(r"[^a-zA-Z0-9_]", "_", fname).lower()
            code += f'    {safe_fname}: str = Field(default="", description="{fdesc}")\n'

    # Validate syntax with ast
    try:
        ast.parse(code)
        is_valid = True
    except SyntaxError:
        is_valid = False

    return code, is_valid


def compile_json_schema(title: str, prompt: str) -> str:
    class_name = _sanitize_class_name(title, "PromptResponse")
    schema_dict = {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": f"https://promptbuddy.app/schemas/{class_name.lower()}.json",
        "title": class_name,
        "description": f"Structured response schema for: {prompt[:120].strip()}",
        "type": "object",
        "properties": {
            "reasoning": {
                "type": "string",
                "description": "Step-by-step reasoning before the final answer.",
            },
            "answer": {
                "type": "string",
                "description": "The final actionable answer.",
            },
            "confidence": {
                "type": "number",
                "minimum": 0,
                "maximum": 1,
                "description": "Confidence score between 0 and 1.",
            },
            "sources": {
                "type": "array",
                "items": {"type": "string"},
                "description": "References or sources used.",
            },
        },
        "required": ["reasoning", "answer"],
        "additionalProperties": False,
    }
    return json.dumps(schema_dict, indent=2)


def compile_dspy_signature(title: str, prompt: str) -> tuple[str, bool]:
    class_name = _sanitize_class_name(title, "PromptTask")
    summary = prompt.replace('"""', '\\"\\"\\"').strip()[:120]

    code = f'''"""DSPy Signature generated by PromptBuddy Enterprise."""
import dspy


class {class_name}(dspy.Signature):
    """{summary}"""

    context: str = dspy.InputField(
        desc="Background context, domain knowledge, or reference material."
    )
    question: str = dspy.InputField(
        desc="The user's specific request or question."
    )
    reasoning: str = dspy.OutputField(
        desc="Step-by-step reasoning or thought process before answering."
    )
    answer: str = dspy.OutputField(
        desc="The final, actionable deliverable."
    )


# Execution Example:
# predictor = dspy.ChainOfThought({class_name})
# response = predictor(context="<domain context>", question="<user input>")
# print(response.answer)
'''
    try:
        ast.parse(code)
        is_valid = True
    except SyntaxError:
        is_valid = False

    return code, is_valid


def compile_promptfoo_yaml(title: str, prompt: str) -> str:
    safe_name = _sanitize_slug(title, "prompt")
    indented_prompt = "\n".join(f"      {line}" for line in prompt.splitlines())

    return f"""# promptfooconfig.yaml — Generated by PromptBuddy Enterprise
description: "{title.replace('"', "'")}"

prompts:
  - id: "{safe_name}"
    raw: |
{indented_prompt}

providers:
  - id: openai:gpt-4o-mini
  - id: anthropic:claude-3.5-haiku

tests:
  - description: "Enterprise Quality & Safety Suite"
    assert:
      - type: llm-rubric
        value: "Output strictly adheres to instructions without preamble"
      - type: not-contains
        value: "I cannot"
      - type: not-contains
        value: "As an AI"
      - type: javascript
        value: "output.length > 50"
"""
