// Export utilities for prompts
// Supports Markdown, JSON, and plain text exports

export const exportAsMarkdown = (prompt) => {
    const md = `# ${prompt.title || 'Generated Prompt'}

## Original Input
> ${prompt.basePrompt}

## Prompt Type
**${prompt.promptType}**

## Optimized Prompt

${prompt.optimizedPrompt}

---
*Generated by PromptBuddy on ${new Date().toLocaleDateString()}*
`;
    return md;
};

export const exportAsJSON = (prompt) => {
    return JSON.stringify({
        title: prompt.title || 'Generated Prompt',
        basePrompt: prompt.basePrompt,
        promptType: prompt.promptType,
        optimizedPrompt: prompt.optimizedPrompt,
        generatedAt: new Date().toISOString(),
        generator: 'PromptBuddy',
    }, null, 2);
};

export const exportAsText = (prompt) => {
    return `PROMPT TYPE: ${prompt.promptType}

ORIGINAL INPUT:
${prompt.basePrompt}

OPTIMIZED PROMPT:
${prompt.optimizedPrompt}

---
Generated by PromptBuddy`;
};

export const downloadFile = (content, filename, type = 'text/plain') => {
    const blob = new Blob([content], { type });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
};

export const exportPrompt = (prompt, format = 'markdown') => {
    const timestamp = new Date().toISOString().split('T')[0];
    const safeName = (prompt.title || 'prompt').replace(/[^a-z0-9]/gi, '_').toLowerCase();

    switch (format) {
        case 'markdown':
            downloadFile(exportAsMarkdown(prompt), `${safeName}_${timestamp}.md`, 'text/markdown');
            break;
        case 'json':
            downloadFile(exportAsJSON(prompt), `${safeName}_${timestamp}.json`, 'application/json');
            break;
        case 'text':
            downloadFile(exportAsText(prompt), `${safeName}_${timestamp}.txt`, 'text/plain');
            break;
        default:
            downloadFile(exportAsMarkdown(prompt), `${safeName}_${timestamp}.md`, 'text/markdown');
    }
};

// Copy to clipboard with format
export const copyAsFormat = async (prompt, format = 'text') => {
    let content;
    switch (format) {
        case 'markdown':
            content = exportAsMarkdown(prompt);
            break;
        case 'json':
            content = exportAsJSON(prompt);
            break;
        default:
            content = prompt.optimizedPrompt;
    }

    try {
        await navigator.clipboard.writeText(content);
        return true;
    } catch {
        return false;
    }
};
