// Export utilities for prompts
// Supports Markdown, JSON, Text, Promptfoo YAML, Langfuse JSON,
// Pydantic Model, JSON Schema, and DSPy Signature exports

export const exportAsMarkdown = (prompt) => {
    const md = `# ${prompt.title || 'Generated Prompt'}

## Original Input
${prompt.basePrompt}

## Prompt Type
**${prompt.promptType}**

${prompt.aiModel ? `## AI Model\n${prompt.aiModel}\n` : ''}

## Optimized Prompt

${prompt.optimizedPrompt}

---
*Generated by PromptBuddy on ${new Date().toLocaleDateString()}*
`;
    return md;
};

export const exportAsJSON = (prompt) => {
    return JSON.stringify({
        title: prompt.title || 'Generated Prompt',
        basePrompt: prompt.basePrompt,
        promptType: prompt.promptType,
        optimizedPrompt: prompt.optimizedPrompt,
        aiModel: prompt.aiModel,
        qualityScore: prompt.qualityScore,
        generatedAt: new Date().toISOString(),
        generator: 'PromptBuddy',
    }, null, 2);
};

export const exportAsText = (prompt) => {
    return `PROMPT TYPE: ${prompt.promptType}
${prompt.aiModel ? `AI MODEL: ${prompt.aiModel}\n` : ''}

ORIGINAL INPUT:
${prompt.basePrompt}

OPTIMIZED PROMPT:
${prompt.optimizedPrompt}

---
Generated by PromptBuddy`;
};

export const downloadFile = (content, filename, type = 'text/plain') => {
    try {
        const blob = new Blob([content], { type });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = filename;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
        return true;
    } catch {
        return false;
    }
};

// --- Promptfoo YAML (CI/CD ready) ---
export const exportPromptfooYaml = (prompt) => {
    const safeName = (prompt.title || 'prompt').replace(/[^a-z0-9]/gi, '-').toLowerCase().slice(0, 40);
    return `# promptfooconfig.yaml — Generated by PromptBuddy
# Docs: https://promptfoo.dev/docs/configuration/reference

description: "${prompt.title || 'PromptBuddy Evaluation'}"

prompts:
  - id: "${safeName}"
    raw: |
${(prompt.optimizedPrompt || prompt.basePrompt || '').split('\n').map(l => `      ${l}`).join('\n')}

providers:
  - id: openai:gpt-4o-mini
  - id: anthropic:claude-3.5-haiku

tests:
  - description: "Basic quality check"
    vars:
      input: "${(prompt.basePrompt || '').slice(0, 120).replace(/"/g, "'")}"
    assert:
      - type: llm-rubric
        value: "Response is relevant, complete, and follows the prompt instructions"
      - type: not-contains
        value: "I cannot"
      - type: not-contains
        value: "As an AI"
      - type: javascript
        value: "output.length > 50"
`;
};

// --- Langfuse Prompt JSON ---
export const exportLangfuseJson = (prompt) => {
    return JSON.stringify({
        name: (prompt.title || 'prompt').replace(/[^a-z0-9_-]/gi, '-').toLowerCase().slice(0, 40),
        prompt: prompt.optimizedPrompt || prompt.basePrompt || '',
        type: 'chat',
        config: {
            model: prompt.aiModel || 'gpt-4o-mini',
            temperature: 0.45,
            max_tokens: 2048,
        },
        labels: ['draft'],
        tags: [prompt.promptType || 'rtf'],
        version: 1,
        metadata: {
            framework: prompt.promptType,
            generator: 'PromptBuddy',
            generatedAt: new Date().toISOString(),
        },
    }, null, 2);
};

// --- Python Pydantic BaseModel ---
export const exportPydanticModel = (prompt) => {
    const className = (prompt.title || 'PromptResponse')
        .replace(/[^a-zA-Z0-9 ]/g, '')
        .split(/\s+/)
        .map(w => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
        .join('');

    return `"""Pydantic model generated by PromptBuddy."""
from pydantic import BaseModel, Field


class ${className}(BaseModel):
    """Structured response model for: ${(prompt.title || prompt.basePrompt || '').slice(0, 80)}"""

    reasoning: str = Field(
        ...,
        description="Step-by-step reasoning or chain-of-thought before the final answer."
    )
    answer: str = Field(
        ...,
        description="The final, actionable answer to the user's request."
    )
    confidence: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
        description="Confidence score between 0 and 1."
    )
    sources: list[str] = Field(
        default_factory=list,
        description="References or sources used to generate the answer."
    )


# Usage with OpenAI:
# from openai import OpenAI
# client = OpenAI()
# completion = client.beta.chat.completions.parse(
#     model="gpt-4o-mini",
#     messages=[
#         {"role": "system", "content": <your_prompt>},
#         {"role": "user", "content": <user_input>},
#     ],
#     response_format=${className},
# )
# result = completion.choices[0].message.parsed
`;
};

// --- JSON Schema (Draft 2020-12) ---
export const exportJsonSchema = (prompt) => {
    const title = (prompt.title || 'PromptResponse')
        .replace(/[^a-zA-Z0-9 ]/g, '')
        .split(/\s+/)
        .map(w => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
        .join('');

    return JSON.stringify({
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": `https://promptbuddy.app/schemas/${title.toLowerCase()}.json`,
        "title": title,
        "description": `Structured response schema for: ${(prompt.title || prompt.basePrompt || '').slice(0, 120)}`,
        "type": "object",
        "properties": {
            "reasoning": {
                "type": "string",
                "description": "Step-by-step reasoning before the final answer."
            },
            "answer": {
                "type": "string",
                "description": "The final, actionable answer."
            },
            "confidence": {
                "type": "number",
                "minimum": 0,
                "maximum": 1,
                "description": "Confidence score between 0 and 1."
            },
            "sources": {
                "type": "array",
                "items": { "type": "string" },
                "description": "References or sources used."
            }
        },
        "required": ["reasoning", "answer"],
        "additionalProperties": false,
    }, null, 2);
};

// --- DSPy Signature ---
export const exportDspySignature = (prompt) => {
    const className = (prompt.title || 'PromptTask')
        .replace(/[^a-zA-Z0-9 ]/g, '')
        .split(/\s+/)
        .map(w => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
        .join('');

    return `"""DSPy Signature generated by PromptBuddy."""
import dspy


class ${className}(dspy.Signature):
    """${(prompt.title || prompt.basePrompt || 'Execute the requested task').slice(0, 120)}"""

    context: str = dspy.InputField(
        desc="Background context, domain knowledge, or reference material."
    )
    question: str = dspy.InputField(
        desc="The user's specific question or task request."
    )
    reasoning: str = dspy.OutputField(
        desc="Step-by-step reasoning before the final answer."
    )
    answer: str = dspy.OutputField(
        desc="The final, actionable answer."
    )


# Usage:
# predictor = dspy.ChainOfThought(${className})
# result = predictor(
#     context="<domain context>",
#     question="<user question>",
# )
# print(result.answer)
`;
};

// Export Microsoft Guidance Program (.py)
export const exportGuidanceProgram = (prompt) => {
    const escaped = (prompt.optimizedPrompt || '').replace(/"""/g, '\\"\\"\\"');
    return `import guidance
from guidance import models, gen, select, system, user, assistant

# PromptBuddy Compiled Guidance Program
# Target Model: OpenAI / Azure / Local Llama
model = models.OpenAI("gpt-4o")

with system():
    lm = model + """${escaped}"""

with user():
    lm += "Execute requested operation with strict compliance."

with assistant():
    lm += gen("response", max_tokens=1000, temperature=0.2)

print(lm["response"])
`;
};

// Export Outlines Regex & Grammar Specification (.py)
export const exportOutlinesGrammar = (prompt) => {
    return `# PromptBuddy Outlines / Regex Grammar Specification
# Constrained generation using Outlines regex-guided decoding

import outlines
from pydantic import BaseModel, Field

# Outlines regex pattern for structured enterprise responses:
regex_pattern = r"(SUCCESS|COMPLIANT|NEEDS_REVIEW): [\\w\\s.,!?-]{10,250}"

# Example Outlines model invocation:
# model = outlines.models.openai("gpt-4o")
# generator = outlines.generate.regex(model, regex_pattern)
# result = generator("""${(prompt.optimizedPrompt || '').slice(0, 120).replace(/"""/g, '\\"\\"\\"')}""")
`;
};

// --- Main export dispatcher ---
export const exportPrompt = (prompt, format = 'markdown') => {
    const timestamp = new Date().toISOString().split('T')[0];
    const safeName = (prompt.title || 'prompt').replace(/[^a-z0-9]/gi, '_').toLowerCase().slice(0, 80);

    switch (format) {
        case 'markdown':
            return downloadFile(exportAsMarkdown(prompt), `${safeName}_${timestamp}.md`, 'text/markdown');
        case 'json':
            return downloadFile(exportAsJSON(prompt), `${safeName}_${timestamp}.json`, 'application/json');
        case 'text':
            return downloadFile(exportAsText(prompt), `${safeName}_${timestamp}.txt`, 'text/plain');
        case 'promptfoo':
            return downloadFile(exportPromptfooYaml(prompt), `promptfooconfig.yaml`, 'text/yaml');
        case 'langfuse':
            return downloadFile(exportLangfuseJson(prompt), `${safeName}_langfuse.json`, 'application/json');
        case 'pydantic':
            return downloadFile(exportPydanticModel(prompt), `${safeName}_model.py`, 'text/x-python');
        case 'jsonschema':
            return downloadFile(exportJsonSchema(prompt), `${safeName}_schema.json`, 'application/json');
        case 'dspy':
            return downloadFile(exportDspySignature(prompt), `${safeName}_signature.py`, 'text/x-python');
        case 'guidance':
            return downloadFile(exportGuidanceProgram(prompt), `${safeName}_guidance.py`, 'text/x-python');
        case 'grammar':
            return downloadFile(exportOutlinesGrammar(prompt), `${safeName}_grammar.py`, 'text/x-python');
        default:
            return downloadFile(exportAsMarkdown(prompt), `${safeName}_${timestamp}.md`, 'text/markdown');
    }
};

// Copy to clipboard with format
export const copyAsFormat = async (prompt, format = 'text') => {
    let content;
    switch (format) {
        case 'markdown':
            content = exportAsMarkdown(prompt);
            break;
        case 'json':
            content = exportAsJSON(prompt);
            break;
        case 'promptfoo':
            content = exportPromptfooYaml(prompt);
            break;
        case 'langfuse':
            content = exportLangfuseJson(prompt);
            break;
        case 'pydantic':
            content = exportPydanticModel(prompt);
            break;
        case 'jsonschema':
            content = exportJsonSchema(prompt);
            break;
        case 'dspy':
            content = exportDspySignature(prompt);
            break;
        case 'guidance':
            content = exportGuidanceProgram(prompt);
            break;
        case 'grammar':
            content = exportOutlinesGrammar(prompt);
            break;
        default:
            content = prompt.optimizedPrompt;
    }

    try {
        await navigator.clipboard.writeText(content);
        return true;
    } catch {
        return false;
    }
};
